spring:
  application:
    name: jiangdaxian-gateway-zuul
  profiles: dev
server:
  port: 8050
eureka:
  instance:
    appname: jiangdaxian-gateway-zuul
    prefer-ip-address: false
  client:
    serviceUrl:
      defaultZone: http://dis1:8761/eureka/,http://dis2:8761/eureka/,http://dis3:8761/eureka/
zuul:
  routes:
    test4:
      path: /test4/**
      stripPrefix: false;
      serviceId: jiangdaxian-gateway-zuul_test_4
    test5:
      path: /test5/**
      stripPrefix: false;
      serviceId: jiangdaxian-gateway-zuul_test_5
