spring:
  application:
    name: jiangdaxian-gateway-zuul
  profiles: dev
server:
  port: 8050
eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      default-zone: http://discovery1:8761/eureka/,http://discovery2:8762/eureka/, http://discovery3:8763/eureka/
    fetch-registry: true
    register-with-eureka: true
zuul:
  routes:
    api-1:
      path: /properties/**
      serviceId: jiangdaxian-gateway-zuul_test
    api-2:
      path: /properties1/**
      serviceId: jiangdaxian-gateway-zuul_test